config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  resources :books, only: [:index, :create, :edit, :update, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true, on: [:create, :update]
  validates :body, presence: true, on: [:create, :update]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_url(@book)
    else
      # ページ遷移したときにindexアクションが呼ばれるわけではなく、
      # indexテンプレが呼ばれるだけなので@booksの初期化が必要。
      # オブジェクト(@book)はindexアクションで生成して、見つけてきているので初期化の必要はない
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_url
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:success] = "Book was successfully destroyed."
    redirect_to books_url
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<%= form_with model: @book, url: book_url(@book), local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Update Book' %>
<% end %>

<%= link_to "show", @book %>
<span> | </span>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>
  <tbody>
    <% if @books %>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
          <td>
            <%= link_to "Show", book %>
            <%= link_to "Edit", edit_book_path(book) %>
            <%= link_to "Destroy", book_path(book), method: :delete %>
          </td>
        </tr>
      <% end %>
    <% end %>
    <tr>
      <td></td>
    </tr>
  </tbody>
</table>

<h2>New book</h2>
<%= form_with model: @book, local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<h1>詳細ページです</h1>
<h3>ここにエラーメッセージ</h3>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
  <br>
  <strong>Body:</strong>
  <%= @book.body %>
</p>

<%= link_to "edit", edit_book_path(@book) %>
<span> | </span>
<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h1>トップページです</h1>
<p>
  <string>Bookers</string>
  " では、さまざまな書籍に関するあなたの意見や

  <p>印象を共有し交換することができます</p>
</p>
<p>
  <%= link_to "start", books_path %>
</p>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div>
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this book from being saved:</h2>
  </div>
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% if flash.any? %>
  <% flash.each do |message_type, message| %>
        <%= message %>
  <% end %>
<% end %>